import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Seyam",
  description: "Generated by E-Seyam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <audio autoPlay loop hidden>
          <source
            src="/صوت رعب بدون موسيقى - nana nana (youtube).mp3"
            type="audio/mp3"
          />
        </audio>
        {/* <CustomCursor/> */}
        {children}
      </body>
    </html>
  );
}
